### ISSUE TITLE
Error no kernel image is available for execution on the device at line 479 in file D:\ai\tool\bitsandbytes\csrc\ops.cu

### ISSUE THREAD

**Issue by magicwang1111** [Vision-CAIR/MiniGPT-4#156]
binary_path: C:\AIGC\MiniGPT-4\bitsandbytes-windows\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary C:\AIGC\MiniGPT-4\bitsandbytes-windows\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Loading checkpoint shards:   0%|                                                                 | 0/3 [00:00<?, ?it/s]Error no kernel image is available for execution on the device at line 479 in file D:\ai\tool\bitsandbytes\csrc\ops.cu

(minigpt4) C:\AIGC\MiniGPT-4>

**Comment by magicwang1111** [comment]
V100    WINDOWS10

**Comment by magicwang1111** [comment]
![9682516a7f8b0baf537f8aba7478fa12](https://user-images.githubusercontent.com/131337141/234525920-bf477c20-54b1-438d-a42d-992ad380e097.png)

**Comment by quartets** [comment]
My problem solved. It was the non-proper installation of bitsandbytes package.
I did an uninstall and then:
pip install https://github.com/acpopescu/bitsandbytes/releases/download/v0.37.2-win.1/bitsandbytes-0.37.2-py3-none-any.whl

Then the MiniGPT-4 can start without any futher error message.

Thanks to the redit post by @oobabooga.
https://www.reddit.com/r/Oobabooga/comments/12eniem/bitsandbytes_now_for_windows_8bit_cuda_functions/

Magic Wang同学：我估计你也是按照《MiniGPT-4本地部署，纯新手小白踩过的坑》一文部署的Windows安装，他文中装bitsandbytes组件的那一步可能有问题，所以删了按上面的语句重装一遍，我遇到的问题就解决了。希望对你也有帮助。

那篇指南还是很棒的，引导我这个小白走到了最后一步，不然再Ubuntu上自行安装，虽然有ChatGPT助力也很难，我已经在Ubuntu上浪费了一天放弃了。

给作者点赞！
https://xlch.wolai.com/pBtGyPh6hyGx118o4deTk

**Comment by K-tang-mkv** [comment]
maybe the torch version doesn't support your cuda version. offical torch version only support cuda10.2, but yours is 11.above, so just upgrade torch version, it gonna work.

**Comment by XDhyao** [comment]
> My problem solved. It was the non-proper installation of bitsandbytes package. I did an uninstall and then: pip install https://github.com/acpopescu/bitsandbytes/releases/download/v0.37.2-win.1/bitsandbytes-0.37.2-py3-none-any.whl
> 
> Then the MiniGPT-4 can start without any futher error message.
> 
> Thanks to the redit post by @oobabooga. https://www.reddit.com/r/Oobabooga/comments/12eniem/bitsandbytes_now_for_windows_8bit_cuda_functions/
> 
> Magic Wang同学：我估计你也是按照《MiniGPT-4本地部署，纯新手小白踩过的坑》一文部署的Windows安装，他文中装bitsandbytes组件的那一步可能有问题，所以删了按上面的语句重装一遍，我遇到的问题就解决了。希望对你也有帮助。
> 
> 那篇指南还是很棒的，引导我这个小白走到了最后一步，不然再Ubuntu上自行安装，虽然有ChatGPT助力也很难，我已经在Ubuntu上浪费了一天放弃了。
> 
> 给作者点赞！ https://xlch.wolai.com/pBtGyPh6hyGx118o4deTk

nice! it work for me

**Comment by djm0539** [comment]
你好请问您解决了吗 遇到了同样的问题！Hello, have you solved it? I encountered the same problem!
