### ISSUE TITLE
Stuck when using multi gpus in stage2 finetuning

### ISSUE THREAD

**Issue by waltonfuture** [Vision-CAIR/MiniGPT-4#288]
I got stuck when using two 3090 gpus in stage2 finetuning. There is no error reported.

`
| distributed init (rank 1, world 2): env://
`
`
| distributed init (rank 0, world 2): env://
`

**Comment by Gary2018X** [comment]
hi  bro have you solved it yet？

**Comment by waltonfuture** [comment]
> hi bro have you solved it yet？

I reinstall my Ubuntu and it works.
